name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: npm install, build and test
      run: |
        npm install
        npm install @quasar/cli
        ./node_modules/.bin/quasar build
